# Project: Queue
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = obj/main.o obj/queue.o $(RES)
LINKOBJ  = obj/main.o obj/queue.o $(RES)
LIBS =  -L"D:/Dev-Cpp/lib"  -s 
INCS =  -I"D:/Dev-Cpp/include"  -I"include" 
CXXINCS =  -I"D:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/Dev-Cpp/include/c++/3.4.2/backward"  -I"D:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"D:/Dev-Cpp/include/c++/3.4.2"  -I"D:/Dev-Cpp/include"  -I"include" 
BIN  = bin/Queue.a
CXXFLAGS = $(CXXINCS)   -ansi -fexpensive-optimizations -O3
CFLAGS = $(INCS)   -ansi -fexpensive-optimizations -O3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before bin/Queue.a all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(LINKOBJ)
	ar r $(BIN) $(LINKOBJ)
	ranlib $(BIN)

obj/main.o: src/main.c
	$(CC) -c src/main.c -o obj/main.o $(CFLAGS)

obj/queue.o: src/queue.c
	$(CC) -c src/queue.c -o obj/queue.o $(CFLAGS)
